# Generated by Django 3.1.2 on 2020-10-17 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20201017_2355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('Can_mark_retuned', 'Set book as returned'),)},
        ),
    ]
