# Generated by Django 3.1.2 on 2020-10-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'On Loan'), ('a', 'Available'), ('r', 'Received'), ('R', 'Retuned')], default='m', help_text='Book Availability', max_length=1),
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
    ]
